services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moneydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: money-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/moneydb?sslmode=disable"

volumes:
  postgres_data:
